workflows:
  version: 2
  main:
    jobs:
      - build
      - publish:
          requires:
            - build
          filters:
            branches:
              only: master

version: 2
jobs:
  build:
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: "Build Docker image"
          command: docker build -t warrenseymour/chrome-extension:$CIRCLE_SHA1 .

  publish:
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: "Verify if our previous image is available"
          command: |
            if ! docker image inspect warrenseymour/chrome-extension:$CIRCLE_SHA1; then
              echo "Previously built image not found for some reason. Building."
              docker build -t warrenseymour/chrome-extension:$CIRCLE_SHA1 .
            fi
      - run:
          name: "Publish images to Docker Hub if neccessary"
          command: |
            docker images --format "{{.ID}}" warrenseymour/chrome-extension:$CIRCLE_SHA1 > current_image_id
            [ -s current_image_id ] || echo "n/a" > current_image_id

            # if IDs match, this image already exists and has been pushed so don't do it again
            if docker images --format "{{.ID}}" warrenseymour/chrome-extension:latest | diff - current_image_id;then
              echo "The image just built (warrenseymour/chrome-extension:${CIRCLE_SHA1}) is the same as latest (warrenseymour/chrome-extension:latest). So, we're not going to push to Docker Hub."
              exit
            fi

            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker tag warrenseymour/chrome-extension:$CIRCLE_SHA1 warrenseymour/chrome-extension:latest
            docker push warrenseymour/chrome-extension:$CIRCLE_SHA1
            docker push warrenseymour/chrome-extension:latest
